import christmasImg from "../images/christmas.jpg";
import thanksgivingImg from "../images/thanksgiving.jpg";

const currentDate = new Date();
const currentYear = currentDate.getFullYear();

function getNextOccurrenceDate(month, day) {
  let date = new Date(currentYear, month, day);
  if (date <= currentDate) {
    date.setFullYear(currentYear + 1);
  }
  return date;
}

export const holidays = [
  {
    key: "new-years",
    name: "New Year's Day",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: true,
    date: getNextOccurrenceDate(0, 1),
  },
  {
    key: "mlk-day",
    name: "Martin Luther King, Jr. Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(0, 15),
  },
  {
    key: "valentines-day",
    name: "Valentine's Day",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(1, 14),
  },
  {
    key: "presidents-day",
    name: "Presidents Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(1, 19),
  },
  {
    key: "international-womens-day",
    name: "International Women's Day",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(2, 8),
  },
  {
    key: "st-patricks-day",
    name: "St. Patrick's Day",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(2, 17),
  },
  {
    key: "earth-day",
    name: "Earth Day",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(3, 22),
  },
  {
    key: "cinco-de-mayo",
    name: "Cinco de Mayo",
    global: false,
    countryCode: "US",
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(4, 5),
  },
  {
    key: "memorial-day",
    name: "Memorial Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(4, 27),
  },
  {
    key: "juneteenth",
    name: "Juneteenth National Independence Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(5, 19),
  },
  {
    key: "independence-day",
    name: "Independence Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(6, 4),
  },
  {
    key: "labor-day",
    name: "Labor Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(8, 2),
  },
  {
    key: "columbus-day",
    name: "Columbus Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(9, 14),
  },
  {
    key: "indigenous-peoples-day",
    name: "Indigenous Peoples' Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(9, 14),
  },
  {
    key: "halloween",
    name: "Halloween",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(9, 31),
  },
  {
    key: "veterans-day",
    name: "Veterans Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(10, 11),
  },
  {
    key: "thanksgiving",
    name: "Thanksgiving Day",
    global: false,
    countryCode: "US",
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(10, 28),
  },
  {
    key: "christmas-eve",
    name: "Christmas Eve",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(11, 24),
  },

  {
    key: "christmas",
    name: "Christmas Day",
    global: true,
    countryCode: null,
    fixed: false,
    isHoliday: true,
    date: getNextOccurrenceDate(11, 25),
  },
  {
    key: "new-years-eve",
    name: "New Year's Eve",
    global: true,
    countryCode: null,
    fixed: true,
    isHoliday: false,
    date: getNextOccurrenceDate(11, 31),
  },
];
